const constants = {
    DATABASE_CONNECTION: 'DATABASE_CONNECTION',
    // VEHICLE_MODEL: 'VEHICLE_MODEL',
    // MAINTENANCE_MODEL: 'MAINTENANCE_MODEL',
    // TRACKING_MODEL: 'TRACKING_MODEL',
  };
  
  export default constants;